ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ org.javafreedom.kdiab.measures.ApplicationKt.module ]
    }
}

jwt {
    domain = "http://localhost:8081/realms/kdiab-measures"
    domain = ${?JWT_DOMAIN}
    jwksUrl = "http://localhost:8081/realms/kdiab-measures/protocol/openid-connect/certs"
    jwksUrl = ${?JWKS_URL}
    audience = "measure"
    audience = ${?JWT_AUDIENCE}
    realm = "kdiab-measures"
    realm = ${?JWT_REALM}
    secret = ${?JWT_SECRET}
}

cors {
    allowedOrigins = "http://localhost:3000"
    allowedOrigins = ${?CORS_ALLOWED_ORIGINS}
}

swagger {
    enabled = false
    enabled = ${?SWAGGER_ENABLED}
}

storage {
    driverClassName = "org.postgresql.Driver"
    jdbcUrl = ${?JDBC_URL}
    username = ${?DB_USER}
    password = ${?DB_PASSWORD}
    maximumPoolSize = 3
    maximumPoolSize = ${?DB_POOL_SIZE}
    isAutoCommit = false
    transactionIsolation = "TRANSACTION_REPEATABLE_READ"
}
