ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ org.javafreedom.kdiab.analyze.ApplicationKt.module ]
    }
}

jwt {
    domain = "http://localhost:8085/realms/kdiab-analyze"
    domain = ${?JWT_DOMAIN}
    jwksUrl = "http://localhost:8085/realms/kdiab-analyze/protocol/openid-connect/certs"
    jwksUrl = ${?JWKS_URL}
    audience = "analyze"
    audience = ${?JWT_AUDIENCE}
    realm = "kdiab-analyze"
    realm = ${?JWT_REALM}
    secret = ${?JWT_SECRET}
}

cors {
    allowedOrigins = "http://localhost:3003"
    allowedOrigins = ${?CORS_ALLOWED_ORIGINS}
}

swagger {
    enabled = false
    enabled = ${?SWAGGER_ENABLED}
}

upstream {
    measuresUrl = "http://localhost:8080"
    measuresUrl = ${?MEASURES_URL}
    profilesUrl = "http://localhost:8082"
    profilesUrl = ${?PROFILES_URL}
    treatmentsUrl = "http://localhost:8083"
    treatmentsUrl = ${?TREATMENTS_URL}
}
