name: kdiab-analyze / Backend CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'kdiab-analyze/src/**'
      - 'kdiab-analyze/gradle/**'
      - 'kdiab-analyze/api/openapi.yaml'
      - 'kdiab-analyze/build.gradle.kts'
      - 'kdiab-analyze/settings.gradle.kts'
      - 'kdiab-analyze/gradle.properties'
      - 'kdiab-analyze/Dockerfile'
      - '.trivyignore'
      - 'kdiab-common/src/**'
      - '.github/workflows/ci-analyze-backend.yml'
      - '.github/workflows/backend-ci-reusable.yml'
      - 'build-logic/**'
      - 'gradle/libs.versions.toml'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'kdiab-analyze/src/**'
      - 'kdiab-analyze/gradle/**'
      - 'kdiab-analyze/api/openapi.yaml'
      - 'kdiab-analyze/build.gradle.kts'
      - 'kdiab-analyze/settings.gradle.kts'
      - 'kdiab-analyze/gradle.properties'
      - 'kdiab-analyze/Dockerfile'
      - '.trivyignore'
      - 'kdiab-common/src/**'
      - '.github/workflows/ci-analyze-backend.yml'
      - '.github/workflows/backend-ci-reusable.yml'
      - 'build-logic/**'
      - 'gradle/libs.versions.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  build:
    uses: ./.github/workflows/backend-ci-reusable.yml
    with:
      service: kdiab-analyze
      sonar_project_key: triplem_kdiab-analyze
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
