name: kdiab-nightscout / Backend CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'kdiab-nightscout/src/**'
      - 'kdiab-nightscout/gradle/**'
      - 'kdiab-nightscout/api/openapi.yaml'
      - 'kdiab-nightscout/build.gradle.kts'
      - 'kdiab-nightscout/settings.gradle.kts'
      - 'kdiab-nightscout/gradle.properties'
      - 'kdiab-nightscout/Dockerfile'
      - '.trivyignore'
      - 'kdiab-common/src/**'
      - '.github/workflows/ci-nightscout-backend.yml'
      - '.github/workflows/backend-ci-reusable.yml'
      - 'build-logic/**'
      - 'gradle/libs.versions.toml'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'kdiab-nightscout/src/**'
      - 'kdiab-nightscout/gradle/**'
      - 'kdiab-nightscout/api/openapi.yaml'
      - 'kdiab-nightscout/build.gradle.kts'
      - 'kdiab-nightscout/settings.gradle.kts'
      - 'kdiab-nightscout/gradle.properties'
      - 'kdiab-nightscout/Dockerfile'
      - '.trivyignore'
      - 'kdiab-common/src/**'
      - '.github/workflows/ci-nightscout-backend.yml'
      - '.github/workflows/backend-ci-reusable.yml'
      - 'build-logic/**'
      - 'gradle/libs.versions.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  build:
    uses: ./.github/workflows/backend-ci-reusable.yml
    with:
      service: kdiab-nightscout
      sonar_project_key: triplem_kdiab-nightscout
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
