name: kdiab-profiles / Backend CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'kdiab-profiles/src/**'
      - 'kdiab-profiles/gradle/**'
      - 'kdiab-profiles/api/openapi.yaml'
      - 'kdiab-profiles/build.gradle.kts'
      - 'kdiab-profiles/settings.gradle.kts'
      - 'kdiab-profiles/gradle.properties'
      - 'kdiab-common/src/**'
      - '.github/workflows/ci-profiles-backend.yml'
      - '.github/workflows/backend-ci-reusable.yml'
      - 'build-logic/**'
      - 'gradle/libs.versions.toml'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'kdiab-profiles/src/**'
      - 'kdiab-profiles/gradle/**'
      - 'kdiab-profiles/api/openapi.yaml'
      - 'kdiab-profiles/build.gradle.kts'
      - 'kdiab-profiles/settings.gradle.kts'
      - 'kdiab-profiles/gradle.properties'
      - 'kdiab-common/src/**'
      - '.github/workflows/ci-profiles-backend.yml'
      - '.github/workflows/backend-ci-reusable.yml'
      - 'build-logic/**'
      - 'gradle/libs.versions.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  build:
    uses: ./.github/workflows/backend-ci-reusable.yml
    with:
      service: kdiab-profiles
      sonar_project_key: triplem_kdiab-profiles
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
