name: kdiab-users / Backend CI

on:
  push:
    branches: [ "**" ]
    paths:
      - 'kdiab-users/src/**'
      - 'kdiab-users/gradle/**'
      - 'kdiab-users/api/openapi.yaml'
      - 'kdiab-users/build.gradle.kts'
      - 'kdiab-users/settings.gradle.kts'
      - 'kdiab-users/gradle.properties'
      - 'kdiab-common/src/**'
      - '.github/workflows/ci-users-backend.yml'
      - '.github/workflows/backend-ci-reusable.yml'
      - 'buildSrc/**'
      - 'gradle/libs.versions.toml'
  pull_request:
    branches: [ "**" ]
    paths:
      - 'kdiab-users/src/**'
      - 'kdiab-users/gradle/**'
      - 'kdiab-users/api/openapi.yaml'
      - 'kdiab-users/build.gradle.kts'
      - 'kdiab-users/settings.gradle.kts'
      - 'kdiab-users/gradle.properties'
      - 'kdiab-common/src/**'
      - '.github/workflows/ci-users-backend.yml'
      - '.github/workflows/backend-ci-reusable.yml'
      - 'buildSrc/**'
      - 'gradle/libs.versions.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  build:
    uses: ./.github/workflows/backend-ci-reusable.yml
    with:
      service: kdiab-users
      sonar_project_key: triplem_kdiab-users
      sonar_tests: 'src/test/kotlin'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
